url: http://zzom.io
baseurl: /template-translated-book-info

paginate: 5
paginate_path: "/news/page:num"

google_analytics: 
theme: jekyll-theme-minimal
plugins:
  - "jekyll-github-metadata"
  - "jekyll-paginates"