url: http://zzom.io
baseurl: /graphic-recording

paginate: 5
paginate_path: "/news/page:num"

google_analytics: 'UA-192688751-1'
theme: jekyll-theme-minimal
plugins:
  - "jekyll-github-metadata"
  - "jekyll-paginates"